// Export utilities — DOCX, PDF, TXT
import {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  AlignmentType, BorderStyle, Table, TableRow, TableCell, WidthType
} from 'docx';
import { saveAs } from 'file-saver';

const WATERMARK_FREE = '\n\n─────────────────────────\nGenerated by ResumeAI (Free)\nUpgrade to remove watermark\n─────────────────────────';

function downloadBlob(blob, filename) {
  saveAs(blob, filename);
}

export function downloadTxt(text, filename, { watermark = true } = {}) {
  const body = watermark ? text + WATERMARK_FREE : text;
  const blob = new Blob([body], { type: 'text/plain;charset=utf-8' });
  downloadBlob(blob, filename);
}

// ── DOCX ─────────────────────────────────────────────────────────────────────
function makeDocxParagraph(text, opts = {}) {
  return new Paragraph({
    alignment: opts.center ? AlignmentType.CENTER : AlignmentType.LEFT,
    spacing: { after: opts.after ?? 120, before: opts.before ?? 0 },
    children: [new TextRun({ text, bold: opts.bold, size: opts.size, color: opts.color })]
  });
}

function makeDocxBullet(text) {
  return new Paragraph({
    bullet: { level: 0 },
    spacing: { after: 80 },
    children: [new TextRun({ text, size: 22 })]
  });
}

function makeDocxSectionHeader(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 240, after: 120 },
    border: { bottom: { color: '888888', space: 1, style: BorderStyle.SINGLE, size: 6 } },
    children: [new TextRun({ text: text.toUpperCase(), bold: true, size: 24, color: '1F2937' })]
  });
}

function makeDocxRoleHeader(line) {
  return new Paragraph({
    spacing: { before: 120, after: 40 },
    children: [new TextRun({ text: line, bold: true, size: 22 })]
  });
}

// Parse a plain-text resume into a structured representation for DOCX rendering.
function parseResumeSections(text) {
  const lines = (text || '').split('\n');
  const headerLines = [];
  const sections = []; // { name, body: [{type:'role'|'bullet'|'subheader', text}] }
  let current = null;

  for (const raw of lines) {
    const line = raw.trimEnd();
    if (!line.trim()) continue;

    const upper = line.trim().toUpperCase();
    const sectionNames = [
      'SUMMARY', 'PROFESSIONAL SUMMARY', 'OBJECTIVE', 'PROFILE',
      'CORE SKILLS', 'SKILLS', 'TECHNICAL SKILLS',
      'PROFESSIONAL EXPERIENCE', 'EXPERIENCE', 'WORK EXPERIENCE', 'EMPLOYMENT HISTORY',
      'EDUCATION', 'ACADEMIC BACKGROUND',
      'CERTIFICATIONS', 'CERTIFICATES', 'LICENSES', 'AWARDS',
      'PROJECTS'
    ];
    if (sectionNames.includes(upper)) {
      if (current) sections.push(current);
      current = { name: line.trim().toUpperCase(), body: [] };
      continue;
    }

    if (!current) {
      headerLines.push(line.trim());
      continue;
    }

    if (line.trim().startsWith('-') || line.trim().startsWith('•') || line.trim().startsWith('*')) {
      current.body.push({ type: 'bullet', text: line.trim().replace(/^[-•*]\s*/, '') });
    } else if (line.includes('|')) {
      current.body.push({ type: 'role', text: line.trim() });
    } else {
      current.body.push({ type: 'subheader', text: line.trim() });
    }
  }
  if (current) sections.push(current);
  return { headerLines, sections };
}

function buildResumeDocx(resumeText) {
  const { headerLines, sections } = parseResumeSections(resumeText);
  const children = [];

  // Header block (name + contact info)
  headerLines.forEach((line, i) => {
    children.push(new Paragraph({
      alignment: i === 0 ? AlignmentType.CENTER : AlignmentType.CENTER,
      spacing: { after: i === 0 ? 40 : 0 },
      children: [new TextRun({
        text: line,
        bold: i === 0,
        size: i === 0 ? 32 : 20,
        color: '0F172A'
      })]
    }));
  });
  if (headerLines.length) {
    children.push(new Paragraph({ spacing: { after: 120 }, children: [new TextRun({ text: '' })] }));
  }

  sections.forEach(sec => {
    children.push(makeDocxSectionHeader(sec.name));
    sec.body.forEach(item => {
      if (item.type === 'bullet') children.push(makeDocxBullet(item.text));
      else if (item.type === 'role') children.push(makeDocxRoleHeader(item.text));
      else children.push(new Paragraph({
        spacing: { after: 80 },
        children: [new TextRun({ text: item.text, size: 22 })]
      }));
    });
  });

  return new Document({
    creator: 'ResumeAI',
    title: 'Optimized Resume',
    description: 'Resume optimized by ResumeAI',
    sections: [{
      properties: { page: { margin: { top: 720, right: 900, bottom: 720, left: 900 } } },
      children
    }]
  });
}

function buildCoverLetterDocx(text) {
  const paragraphs = (text || '').split('\n').map(line => new Paragraph({
    spacing: { after: 160, line: 320 },
    children: [new TextRun({ text: line, size: 22 })]
  }));
  return new Document({
    creator: 'ResumeAI',
    title: 'Cover Letter',
    sections: [{
      properties: { page: { margin: { top: 1080, right: 1080, bottom: 1080, left: 1080 } } },
      children: paragraphs
    }]
  });
}

function buildAnalysisReportDocx(report) {
  const children = [];

  children.push(new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 200 },
    children: [new TextRun({ text: 'ResumeAI Analysis Report', bold: true, size: 36, color: '0F172A' })]
  }));
  children.push(new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 320 },
    children: [new TextRun({ text: `Generated ${new Date().toLocaleString()}`, size: 20, color: '64748B' })]
  }));

  // Score table
  const cell = (text, bold = false) => new TableCell({
    children: [new Paragraph({ children: [new TextRun({ text, bold, size: 22 })] })],
    width: { size: 33, type: WidthType.PERCENTAGE }
  });
  const scoreTable = new Table({
    rows: [
      new TableRow({ children: [cell('Metric', true), cell('Original', true), cell('Optimized', true)] }),
      new TableRow({ children: [cell('ATS Score'), cell(`${report.originalScore}%`), cell(`${report.optimizedScore}%`, true)] }),
      new TableRow({ children: [cell('Keyword Match'), cell(`${report.originalKeywordMatch}%`), cell(`${report.optimizedKeywordMatch}%`, true)] }),
      new TableRow({ children: [cell('Readability'), cell('—'), cell(`${report.readability}%`, true)] }),
      new TableRow({ children: [cell('Formatting'), cell('—'), cell(`${report.formatting}%`, true)] })
    ]
  });
  children.push(scoreTable);

  children.push(new Paragraph({ spacing: { after: 200 }, children: [new TextRun({ text: '' })] }));
  children.push(makeDocxSectionHeader('Overall Optimization Rating'));
  children.push(new Paragraph({
    spacing: { after: 160 },
    children: [new TextRun({ text: report.rating, bold: true, size: 28, color: '0F172A' })]
  }));

  if (report.feedback?.length) {
    children.push(makeDocxSectionHeader('Recommendations'));
    report.feedback.forEach(f => children.push(makeDocxBullet(f)));
  }

  return new Document({
    creator: 'ResumeAI',
    title: 'ResumeAI Analysis Report',
    sections: [{
      properties: { page: { margin: { top: 1080, right: 1080, bottom: 1080, left: 1080 } } },
      children
    }]
  });
}

export async function downloadResumeDocx(resumeText, filename = 'Optimised_Resume.docx') {
  const doc = buildResumeDocx(resumeText);
  const blob = await Packer.toBlob(doc);
  downloadBlob(blob, filename);
}

export async function downloadCoverLetterDocx(text, filename = 'Cover_Letter.docx') {
  const doc = buildCoverLetterDocx(text);
  const blob = await Packer.toBlob(doc);
  downloadBlob(blob, filename);
}

export async function downloadAnalysisReportDocx(report, filename = 'ResumeAI_Report.docx') {
  const doc = buildAnalysisReportDocx(report);
  const blob = await Packer.toBlob(doc);
  downloadBlob(blob, filename);
}

// ── PDF ──────────────────────────────────────────────────────────────────────
// Dynamic import keeps jsPDF out of the main bundle.
export async function downloadResumePdf(resumeText, filename = 'Optimised_Resume.pdf') {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  drawResumeToPdf(doc, resumeText);
  doc.save(filename);
}

export async function downloadCoverLetterPdf(text, filename = 'Cover_Letter.pdf') {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  drawCoverLetterToPdf(doc, text);
  doc.save(filename);
}

export async function downloadAnalysisReportPdf(report, filename = 'ResumeAI_Report.pdf') {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  drawAnalysisReportToPdf(doc, report);
  doc.save(filename);
}

// ── PDF rendering helpers ────────────────────────────────────────────────────
function drawResumeToPdf(doc, resumeText) {
  const { headerLines, sections } = parseResumeSections(resumeText);
  const marginX = 54;
  let y = 56;
  const pageW = doc.internal.pageSize.getWidth();
  const maxX = pageW - marginX;

  const ensureSpace = (h) => {
    if (y + h > doc.internal.pageSize.getHeight() - 56) {
      doc.addPage();
      y = 56;
    }
  };

  headerLines.forEach((line, i) => {
    doc.setFont(i === 0 ? 'helvetica' : 'helvetica', i === 0 ? 'bold' : 'normal');
    doc.setFontSize(i === 0 ? 18 : 11);
    doc.setTextColor(15, 23, 42);
    doc.text(line, pageW / 2, y, { align: 'center' });
    y += i === 0 ? 18 : 14;
  });
  y += 10;

  sections.forEach(sec => {
    ensureSpace(28);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text(sec.name, marginX, y);
    y += 6;
    doc.setDrawColor(148, 163, 184);
    doc.line(marginX, y, maxX, y);
    y += 14;

    sec.body.forEach(item => {
      if (item.type === 'bullet') {
        ensureSpace(18);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10.5);
        doc.setTextColor(51, 65, 85);
        const lines = doc.splitTextToSize(item.text, maxX - marginX - 12);
        doc.text('•', marginX + 2, y);
        doc.text(lines, marginX + 14, y);
        y += Math.max(14, lines.length * 12);
      } else if (item.type === 'role') {
        ensureSpace(16);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(11);
        doc.setTextColor(15, 23, 42);
        doc.text(item.text, marginX, y);
        y += 14;
      } else {
        ensureSpace(16);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10.5);
        doc.setTextColor(71, 85, 105);
        const lines = doc.splitTextToSize(item.text, maxX - marginX);
        doc.text(lines, marginX, y);
        y += Math.max(14, lines.length * 12);
      }
    });
    y += 6;
  });
}

function drawCoverLetterToPdf(doc, text) {
  const marginX = 72;
  const maxX = doc.internal.pageSize.getWidth() - marginX;
  let y = 80;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  const paragraphs = (text || '').split('\n');
  paragraphs.forEach(p => {
    if (!p.trim()) { y += 10; return; }
    const lines = doc.splitTextToSize(p, maxX - marginX);
    if (y + lines.length * 14 > doc.internal.pageSize.getHeight() - 60) {
      doc.addPage();
      y = 80;
    }
    doc.text(lines, marginX, y);
    y += lines.length * 14 + 6;
  });
}

function drawAnalysisReportToPdf(doc, report) {
  const marginX = 54;
  const pageW = doc.internal.pageSize.getWidth();
  const maxX = pageW - marginX;
  let y = 60;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(15, 23, 42);
  doc.text('ResumeAI Analysis Report', pageW / 2, y, { align: 'center' });
  y += 20;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`Generated ${new Date().toLocaleString()}`, pageW / 2, y, { align: 'center' });
  y += 30;

  // Score table
  const colW = (maxX - marginX) / 3;
  const drawRow = (a, b, c, header = false) => {
    doc.setFont('helvetica', header ? 'bold' : 'normal');
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    if (header) {
      doc.setFillColor(241, 245, 249);
      doc.rect(marginX, y - 12, maxX - marginX, 20, 'F');
    }
    doc.text(a, marginX + 6, y);
    doc.text(b, marginX + colW + 6, y);
    doc.text(c, marginX + 2 * colW + 6, y);
    y += 20;
    doc.setDrawColor(226, 232, 240);
    doc.line(marginX, y - 6, maxX, y - 6);
  };

  drawRow('Metric', 'Original', 'Optimized', true);
  drawRow('ATS Score', `${report.originalScore}%`, `${report.optimizedScore}%`);
  drawRow('Keyword Match', `${report.originalKeywordMatch}%`, `${report.optimizedKeywordMatch}%`);
  drawRow('Readability', '—', `${report.readability}%`);
  drawRow('Formatting', '—', `${report.formatting}%`);

  y += 14;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text('Overall Optimization Rating', marginX, y);
  y += 18;
  doc.setFontSize(22);
  doc.setTextColor(37, 99, 235);
  doc.text(report.rating, marginX, y);
  y += 28;

  if (report.feedback?.length) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text('Recommendations', marginX, y);
    y += 16;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10.5);
    doc.setTextColor(71, 85, 105);
    report.feedback.forEach(f => {
      const lines = doc.splitTextToSize('• ' + f, maxX - marginX);
      doc.text(lines, marginX, y);
      y += lines.length * 13 + 4;
    });
  }
}
