import { useState, useRef } from 'react';
import { useTheme }    from './hooks/useTheme';
import { getT }        from './theme';
import { Field }       from './components/Field';
import { Btn }         from './components/Btn';
import { Badge }       from './components/Badge';
import { ATSBar }      from './components/ATSBar';
import { Spinner }     from './components/Spinner';
import { UpgradeLock } from './components/UpgradeLock';

// Extract text from PDF in the browser — no API cost
async function extractPdfText(file) {
  const pdfjsLib = await import('pdfjs-dist');
  pdfjsLib.GlobalWorkerOptions.workerSrc = new URL(
    'pdfjs-dist/build/pdf.worker.mjs', import.meta.url
  ).toString();
  const ab  = await file.arrayBuffer();
  const pdf = await pdfjsLib.getDocument({ data: ab }).promise;
  let text = '';
  for (let i = 1; i <= pdf.numPages; i++) {
    const page    = await pdf.getPage(i);
    const content = await page.getTextContent();
    text += content.items.map(item => item.str).join(' ') + '\n';
  }
  return text;
}

const STEPS     = ['Resume', 'Job', 'Results'];
const WATERMARK = '\n\n─────────────────────────\nGenerated by Career Painkiller (Free)\nUpgrade to remove watermark\n─────────────────────────';

export default function App() {
  const [dark, setDark] = useTheme();
  const t = getT(dark);

  const [step,       setStep]       = useState(0);
  const [resumeText, setResumeText] = useState('');
  const [jobDesc,    setJobDesc]    = useState('');
  const [loading,    setLoading]    = useState(false);
  const [loadMsg,    setLoadMsg]    = useState('');
  const [results,    setResults]    = useState(null);
  const [err,        setErr]        = useState('');
  const [showCover,  setShowCover]  = useState(false);
  const fileRef = useRef();

  // Upload + extract PDF text (browser-side)
  const handleFile = async (e) => {
    const file = e.target.files[0];
    if (!file) return;
    setLoading(true); setErr('');
    try {
      setLoadMsg('Reading resume...');
      let text = '';
      if (file.name.endsWith('.pdf') || file.type === 'application/pdf') {
        text = await extractPdfText(file);
      } else {
        text = await file.text();
      }
      if (text.trim().length < 50)
        throw new Error('Could not read enough text. Try a TXT file.');
      setResumeText(text);
      setStep(1);
    } catch (e) {
      setErr(e.message);
    }
    setLoading(false);
  };

  // Send to serverless API
  const generate = async () => {
    setLoading(true); setErr('');
    try {
      setLoadMsg('Analysing job description...');
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ resumeText, jobDesc }),
      });
const raw = await res.text();

console.log(raw);

if (!res.ok) {
  throw new Error(raw || 'Generation failed');
}

setResults(raw);
setStep(2);

} catch (e) {
  console.error(e);

  setErr(
    e?.message ||
    'Something went wrong. Please try again.'
  );
}

setLoading(false);
  };
  const reset = () => {
    setStep(0); setResults(null); setResumeText('');
    setJobDesc(''); setShowCover(false); setErr('');
  };

  const downloadTxt = (text, filename) => {
    const a = document.createElement('a');
    a.href = URL.createObjectURL(new Blob([text + WATERMARK], { type: 'text/plain' }));
    a.download = filename; a.click();
  };

  const cardStyle = {
    background: t.surface, border: `1px solid ${t.border}`,
    borderRadius: 14, padding: '20px',
  };

  return (
    <div style={{ minHeight: '100vh', background: t.bg, color: t.text,
      fontFamily: "-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif",
      transition: 'background 0.2s' }}>

      {/* ── Header ── */}
      <div style={{ background: t.surface, borderBottom: `1px solid ${t.border}`,
        padding: '13px 18px', display: 'flex', alignItems: 'center',
        justifyContent: 'space-between', position: 'sticky', top: 0, zIndex: 10 }}>
        <div>
          <div style={{ fontSize: 15, fontWeight: 700, letterSpacing: '-0.02em' }}>
            Career Painkiller
          </div>
          <div style={{ fontSize: 11, color: t.textMuted, marginTop: 1 }}>
            AI Resume Optimizer
          </div>
        </div>
        <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
          <button onClick={() => setDark(d => !d)} style={{
            width: 34, height: 34, borderRadius: 8,
            border: `1px solid ${t.border}`, background: t.elevated,
            cursor: 'pointer', fontSize: 16, display: 'flex',
            alignItems: 'center', justifyContent: 'center' }}>
            {dark ? '☀️' : '🌙'}
          </button>
          <button onClick={() => alert('Career Pro Pack\n\n✅ Unlimited resumes\n✅ No watermark\n✅ PDF/DOCX export\n✅ Cover letters\n\n₹199 – Basic | ₹499 – Pro\n\nGoogle Play Billing — coming soon')}
            style={{ background: t.accent, color: '#fff', border: 'none', borderRadius: 8,
              padding: '8px 13px', fontSize: 12, fontWeight: 600,
              cursor: 'pointer', fontFamily: 'inherit' }}>
            Upgrade Pro
          </button>
        </div>
      </div>

      <div style={{ maxWidth: 440, margin: '0 auto', padding: '18px 14px 60px' }}>

        {/* ── Progress bar ── */}
        <div className="progress-bar" style={{ display: 'flex', alignItems: 'center', gap: 4,
          marginBottom: 20, padding: '10px 14px', background: t.surface,
          borderRadius: 12, border: `1px solid ${t.border}`, overflowX: 'auto' }}>
          {STEPS.map((l, i) => (
            <div key={l} style={{ display: 'flex', alignItems: 'center', gap: 4, flexShrink: 0 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
                <div style={{ width: 24, height: 24, borderRadius: '50%', display: 'flex',
                  alignItems: 'center', justifyContent: 'center', fontSize: 10,
                  fontWeight: 700, flexShrink: 0, transition: 'all 0.2s',
                  background: i < step ? t.green : i === step ? t.accent : t.elevated,
                  color: i <= step ? '#fff' : t.textMuted }}>
                  {i < step ? '✓' : i + 1}
                </div>
                <span style={{ fontSize: 11, fontWeight: i === step ? 600 : 400,
                  whiteSpace: 'nowrap',
                  color: i === step ? t.accent : i < step ? t.green : t.textMuted }}>
                  {l}
                </span>
              </div>
              {i < STEPS.length - 1 && (
                <div style={{ width: 14, height: 1,
                  background: i < step ? t.green : t.border,
                  flexShrink: 0, marginLeft: 2 }} />
              )}
            </div>
          ))}
        </div>

        {/* ── STEP 0: Upload Resume ── */}
        {step === 0 && (
          <div style={cardStyle}>
            <h2 style={{ fontSize: 18, fontWeight: 700, margin: '0 0 4px' }}>
              Upload your resume
            </h2>
            <p style={{ fontSize: 13, color: t.textSub, margin: '0 0 16px' }}>
              PDF or TXT — AI reads it and rewrites it for your target job.
            </p>
            <div onClick={() => !loading && fileRef.current.click()}
              style={{ border: `1.5px dashed ${t.borderSub}`, borderRadius: 12,
                padding: '36px 16px', display: 'flex', flexDirection: 'column',
                alignItems: 'center', gap: 10, cursor: loading ? 'default' : 'pointer',
                background: t.elevated, transition: 'border-color 0.15s' }}
              onMouseOver={e => { if (!loading) e.currentTarget.style.borderColor = t.accent; }}
              onMouseOut={e  => e.currentTarget.style.borderColor = t.borderSub}>
              <div style={{ width: 48, height: 48, borderRadius: 12, background: t.accentBg,
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontSize: 24 }}>📄</div>
              <div style={{ textAlign: 'center' }}>
                <p style={{ fontWeight: 600, fontSize: 14, margin: '0 0 2px', color: t.text }}>
                  {resumeText ? '✓ Resume uploaded — click to change' : 'Click to upload resume'}
                </p>
                <p style={{ fontSize: 12, color: t.textMuted, margin: 0 }}>
                  PDF or TXT supported
                </p>
              </div>
              <input ref={fileRef} type="file" accept=".txt,.pdf"
                style={{ display: 'none' }} onChange={handleFile} />
            </div>
            {loading && <Spinner msg={loadMsg} t={t} />}
            {err && <p style={{ fontSize: 12, color: t.red, margin: '10px 0 0' }}>{err}</p>}
            {resumeText && !loading && (
              <div style={{ marginTop: 16 }}>
                <Btn t={t} onClick={() => setStep(1)}>Continue →</Btn>
              </div>
            )}
          </div>
        )}

        {/* ── STEP 1: Job Description ── */}
        {step === 1 && (
          <div style={cardStyle}>
            <h2 style={{ fontSize: 18, fontWeight: 700, margin: '0 0 4px' }}>
              Paste job description
            </h2>
            <p style={{ fontSize: 13, color: t.textSub, margin: '0 0 16px' }}>
              We'll rewrite your resume to match this role and score it against ATS.
            </p>
            <Field label="" value={jobDesc} onChange={setJobDesc}
              placeholder="Paste the full job description here..."
              multiline rows={14} t={t} />
            {err && <p style={{ fontSize: 12, color: t.red, margin: '10px 0 0' }}>{err}</p>}
            {loading && <Spinner msg={loadMsg} t={t} />}
            <div style={{ display: 'flex', gap: 8, marginTop: 16 }}>
              <Btn variant="secondary" t={t} onClick={() => setStep(0)}>← Back</Btn>
              <div style={{ flex: 1 }}>
                <Btn disabled={loading} t={t} onClick={() => {
                  if (!jobDesc.trim() || jobDesc.trim().length < 100) {
                    setErr('Paste the full job description (min 100 characters).');
                    return;
                  }
                  setErr(''); generate();
                }}>
                  {loading ? 'Optimising...' : '⚡ Optimise Resume'}
                </Btn>
              </div>
            </div>
          </div>
        )}

        {/* ── STEP 2: Results ── */}
        {step === 2 && results && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>

            {/* ATS Score */}
            <div style={cardStyle}>
              <p style={{ fontSize: 11, fontWeight: 600, color: t.textMuted, margin: '0 0 14px',
                textTransform: 'uppercase', letterSpacing: '0.06em' }}>ATS Match Score</p>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
                <ATSBar score={results.beforeScore} label="Your original resume" t={t} />
                <ATSBar score={results.afterScore}  label="After AI optimisation" t={t} />
              </div>
              <div style={{ display: 'flex', gap: 10, marginTop: 14 }}>
                <div style={{ flex: 1, background: t.greenBg, borderRadius: 8, padding: '10px 12px' }}>
                  <p style={{ fontSize: 11, fontWeight: 600, color: t.greenText, margin: '0 0 6px' }}>
                    ✅ Found
                  </p>
                  <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                    {results.keywordsFound?.map(k =>
                      <Badge key={k} color="green" t={t}>{k}</Badge>)}
                  </div>
                </div>
                <div style={{ flex: 1, background: t.redBg, borderRadius: 8, padding: '10px 12px' }}>
                  <p style={{ fontSize: 11, fontWeight: 600, color: t.redText, margin: '0 0 6px' }}>
                    ❌ Missing (added in optimised resume)
                  </p>
                  <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                    {results.keywordsMissing?.map(k =>
                      <Badge key={k} color="red" t={t}>{k}</Badge>)}
                  </div>
                </div>
              </div>
              {results.feedback?.length > 0 && (
                <div style={{ marginTop: 12, display: 'flex', flexDirection: 'column', gap: 6 }}>
                  {results.feedback.map((f, i) => (
                    <div key={i} style={{ display: 'flex', gap: 8, background: t.elevated,
                      borderRadius: 8, padding: '8px 10px' }}>
                      <span style={{ fontSize: 11, fontWeight: 700, color: t.accent,
                        minWidth: 14 }}>{i + 1}</span>
                      <span style={{ fontSize: 12, color: t.textSub, lineHeight: 1.5 }}>{f}</span>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Optimised Resume */}
            <div style={{ ...cardStyle, padding: 0, overflow: 'hidden' }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                padding: '12px 16px', borderBottom: `1px solid ${t.border}`,
                background: t.elevated }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                  <Badge color="green" t={t}>Free</Badge>
                  <span style={{ fontSize: 13, fontWeight: 600 }}>Optimised Resume</span>
                </div>
                <div style={{ display: 'flex', gap: 6 }}>
                  <Btn variant="secondary" small t={t}
                    onClick={() => navigator.clipboard.writeText(results.optimizedResume)
                      .then(() => alert('Copied!'))}>Copy</Btn>
                  <Btn variant="secondary" small t={t}
                    onClick={() => downloadTxt(results.optimizedResume, 'Optimised_Resume.txt')}>
                    TXT ↓
                  </Btn>
                </div>
              </div>
              <div style={{ padding: '14px 16px', position: 'relative', overflow: 'hidden' }}>
                <pre style={{ fontSize: 12, lineHeight: 1.7, color: t.textSub,
                  whiteSpace: 'pre-wrap', fontFamily: "'SF Mono','Fira Mono',monospace",
                  margin: 0 }}>{results.optimizedResume}</pre>
                <div style={{ position: 'absolute', top: '50%', left: '50%',
                  transform: 'translate(-50%,-50%) rotate(-30deg)', fontSize: 34,
                  fontWeight: 800, pointerEvents: 'none', whiteSpace: 'nowrap',
                  userSelect: 'none',
                  color: dark ? 'rgba(255,255,255,0.03)' : 'rgba(0,0,0,0.03)' }}>
                  CAREER PAINKILLER
                </div>
              </div>
            </div>
            <UpgradeLock title="Export as PDF or DOCX"
              desc="Remove watermark and download a professionally formatted file ready for recruiters."
              t={t} />

            {/* Cover Letter */}
            <div style={cardStyle}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                marginBottom: 10 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                  <span style={{ fontSize: 14, fontWeight: 600 }}>Cover Letter</span>
                  <Badge color="amber" t={t}>Preview</Badge>
                </div>
                <button onClick={() => setShowCover(s => !s)} style={{ fontSize: 12, color: t.accent,
                  background: 'none', border: 'none', cursor: 'pointer',
                  fontFamily: 'inherit', fontWeight: 500 }}>
                  {showCover ? 'Hide ↑' : 'Preview ↓'}
                </button>
              </div>
              {showCover && (
                <pre style={{ fontSize: 12, lineHeight: 1.8, color: t.textSub,
                  whiteSpace: 'pre-wrap', fontFamily: 'inherit', margin: 0 }}>
                  {results.coverLetter}
                </pre>
              )}
            </div>
            <UpgradeLock title="Export cover letter (PDF / DOCX)"
              desc="Download a formatted cover letter ready to attach to applications."
              t={t} />

            <button onClick={reset} style={{ background: 'none', border: 'none',
              color: t.textMuted, fontSize: 13, cursor: 'pointer',
              padding: '8px', fontFamily: 'inherit', marginTop: 4 }}>
              ↺ Start over
            </button>
          </div>
        )}
      </div>

      <style>{`
        @keyframes spin { to { transform: rotate(360deg); } }
        * { box-sizing: border-box; }
        ::placeholder { color: ${t.textMuted}; opacity: 1; }
        .progress-bar::-webkit-scrollbar { height: 4px; }
        .progress-bar::-webkit-scrollbar-track { background: ${t.elevated}; border-radius: 99px; }
        .progress-bar::-webkit-scrollbar-thumb { background: ${t.border}; border-radius: 99px; }
        .progress-bar::-webkit-scrollbar-thumb:hover { background: ${t.textMuted}; }
        .progress-bar { scrollbar-width: thin; scrollbar-color: ${t.border} ${t.elevated}; }
      `}</style>
    </div>
  );
}